// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b3ab8613-e004-48ae-bd53-4778888467f4";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onStatMessagesChange();
void onLeftCurtainStatusChange();
void onRightCurtainStatusChange();

String stat_Messages;
int left_Curtain_Status;
int right_Curtain_Status;
CloudTime morning_time;
CloudTime night_time;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(stat_Messages, READWRITE, ON_CHANGE, onStatMessagesChange);
  ArduinoCloud.addProperty(left_Curtain_Status, READWRITE, ON_CHANGE, onLeftCurtainStatusChange);
  ArduinoCloud.addProperty(right_Curtain_Status, READWRITE, ON_CHANGE, onRightCurtainStatusChange);
  ArduinoCloud.addProperty(morning_time, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(night_time, READ, 30 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
