/* 
  Sketch generated by the Arduino IoT Cloud Thing "curtainbot2"
  https://create.arduino.cc/cloud/things/f0f29bb7-790d-4ab7-8442-8b518f2955b7 
  Arduino IoT Cloud Variables description
  The following variables are automatically generated and updated when changes are made to the Thing
  String stat_Messages;
  int left_Curtain_Status;
  int right_Curtain_Status;
  CloudTime morning_time;
  CloudTime night_time;
  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "thingProperties.h"
#include "control.h"

const int LED_PIN = 2;
bool TestThing = 1;

// Routine control flags
bool morningRoutineEnabled = true;
bool nightRoutineEnabled = true;

struct TimeData {
  int year;
  int month;
  int day;
  int hour;
  int minute;
  int second;
  String formatted;   // "YYYY-MM-DD HH:MM:SS"
};

void setup() {
  controlSetup();
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  // Defined in thingProperties.h
  initProperties();
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you'll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  controlLoop();
  ArduinoCloud.update();
  if (ArduinoCloud.connected()) {
    digitalWrite(LED_PIN, HIGH);
  }
  else {
    digitalWrite(LED_PIN, LOW);
  }
  
  // Check if it's time to trigger morning routine
  if (morningRoutineEnabled) {
    checkMorningTime();
  }
  
  // Check if it's time to trigger night routine
  if (nightRoutineEnabled) {
    checkNightTime();
  }
}

/*
  Since Gps is READ_WRITE variable, onGpsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGpsChange()  {
  // Add your code here to act upon Gps change
}

/*
  Since RightCurtainStatus is READ_WRITE variable, onRightCurtainStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRightCurtainStatusChange()  {
  // Add your code here to act upon RightCurtainStatus change
  status_Update(getStatusString());
}

/*
  Since LeftCurtainStatus is READ_WRITE variable, onLeftCurtainStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLeftCurtainStatusChange()  {
  // Add your code here to act upon LeftCurtainStatus change
  if (left_Curtain_Status == 0) { //stop
    motor2.stop();
  }
  else if (left_Curtain_Status == 1) { //open

  }
  else { //close

  }
  status_Update(getStatusString());
}

TimeData get_time() {
  TimeData td;
  unsigned long t = ArduinoCloud.getLocalTime();
  struct tm *timeInfo = localtime((time_t *)&t);
  td.year   = timeInfo->tm_year + 1900;
  td.month  = timeInfo->tm_mon + 1;
  td.day    = timeInfo->tm_mday;
  td.hour   = timeInfo->tm_hour;
  td.minute = timeInfo->tm_min;
  td.second = timeInfo->tm_sec;
  char buffer[30];
  snprintf(buffer, sizeof(buffer),
           "%04d-%02d-%02d %02d:%02d:%02d",
           td.year, td.month, td.day,
           td.hour, td.minute, td.second);
  td.formatted = String(buffer);
  return td;
}

void status_Update(String msg) {
  TimeData now = get_time();
  stat_Messages = now.formatted + "\n" + msg;
}

// Check if current time matches morning time and trigger once
void checkMorningTime() {
  static bool morningTriggered = false;
  TimeData now = get_time();
  
  // morning_time is stored as minutes since midnight (0-1439)
  int morningMinutesSinceMidnight = morning_time;
  int morningHour = morningMinutesSinceMidnight / 60;
  int morningMinute = morningMinutesSinceMidnight % 60;
  
  // Check if we're within the morning time window (current minute)
  if (now.hour == morningHour && now.minute == morningMinute) {
    if (!morningTriggered) {
      morningTriggered = true;
      
      // TODO: Call function to open curtains
      status_Update("Morning time - opening curtains");
    }
  } else {
    // Reset trigger when we're past the minute
    morningTriggered = false;
  }
}

// Check if current time matches night time and trigger once
void checkNightTime() {
  static bool nightTriggered = false;
  TimeData now = get_time();
  
  // night_time is stored as minutes since midnight (0-1439)
  int nightMinutesSinceMidnight = night_time;
  int nightHour = nightMinutesSinceMidnight / 60;
  int nightMinute = nightMinutesSinceMidnight % 60;
  
  // Check if we're within the night time window (current minute)
  if (now.hour == nightHour && now.minute == nightMinute) {
    if (!nightTriggered) {
      nightTriggered = true;
      
      // TODO: Call function to close curtains
      status_Update("Night time - closing curtains");
    }
  } else {
    // Reset trigger when we're past the minute
    nightTriggered = false;
  }
}

/*
  Since StatMessages is READ_WRITE variable, onStatMessagesChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStatMessagesChange() {
  if (stat_Messages.length() == 0) return;
  
  char command = stat_Messages[0];
  
  switch (command) {
    case 'H': {
      // Help command
      String helpMsg = "COMMANDS:\n";
      helpMsg += "I - Show info\n";
      helpMsg += "MXX:XX - Set morning time\n";
      helpMsg += "Ms - Stop morning routine\n";
      helpMsg += "Mr - Resume morning routine\n";
      helpMsg += "NXX:XX - Set night time\n";
      helpMsg += "Ns - Stop night routine\n";
      helpMsg += "Nr - Resume night routine";
      status_Update(helpMsg);
      break;
    }
    
    case 'I': {
      // Info command - show current settings
      String infoMsg = "=== CURTAIN INFO ===\n";
      
      // Morning time info
      if (morning_time > 0) {
        int mHour = morning_time / 60;
        int mMinute = morning_time % 60;
        char mTimeStr[20];
        snprintf(mTimeStr, sizeof(mTimeStr), "Morning: %02d:%02d", mHour, mMinute);
        infoMsg += String(mTimeStr);
      } else {
        infoMsg += "Morning: Not set";
      }
      infoMsg += morningRoutineEnabled ? " (Active)\n" : " (Inactive)\n";
      
      // Night time info
      if (night_time > 0) {
        int nHour = night_time / 60;
        int nMinute = night_time % 60;
        char nTimeStr[20];
        snprintf(nTimeStr, sizeof(nTimeStr), "Night: %02d:%02d", nHour, nMinute);
        infoMsg += String(nTimeStr);
      } else {
        infoMsg += "Night: Not set";
      }
      infoMsg += nightRoutineEnabled ? " (Active)" : " (Inactive)";
      
      status_Update(infoMsg);
      break;
    }
    
    case 'M': {
      // Morning commands
      if (stat_Messages.length() > 1) {
        char subCommand = stat_Messages[1];
        
        if (subCommand == 's') {
          // Stop morning routine
          morningRoutineEnabled = false;
          status_Update("Morning routine stopped");
        }
        else if (subCommand == 'r') {
          // Resume morning routine
          morningRoutineEnabled = true;
          status_Update("Morning routine resumed");
        }
        else if (subCommand >= '0' && subCommand <= '9') {
          // Set morning time (format: MHH:MM)
          if (stat_Messages.length() >= 6) {
            int hour = (stat_Messages[1] - '0') * 10 + (stat_Messages[2] - '0');
            int minute = (stat_Messages[4] - '0') * 10 + (stat_Messages[5] - '0');
            
            if (hour >= 0 && hour <= 23 && minute >= 0 && minute <= 59) {
              // Store as minutes since midnight
              morning_time = hour * 60 + minute;
              char msg[50];
              snprintf(msg, sizeof(msg), "Morning time set to %02d:%02d", hour, minute);
              status_Update(String(msg));
            } else {
              status_Update("Invalid time format");
            }
          } else {
            status_Update("Invalid command format. Use MHH:MM");
          }
        }
      }
      break;
    }
    
    case 'N': {
      // Night commands
      if (stat_Messages.length() > 1) {
        char subCommand = stat_Messages[1];
        
        if (subCommand == 's') {
          // Stop night routine
          nightRoutineEnabled = false;
          status_Update("Night routine stopped");
        }
        else if (subCommand == 'r') {
          // Resume night routine
          nightRoutineEnabled = true;
          status_Update("Night routine resumed");
        }
        else if (subCommand >= '0' && subCommand <= '9') {
          // Set night time (format: NHH:MM)
          if (stat_Messages.length() >= 6) {
            int hour = (stat_Messages[1] - '0') * 10 + (stat_Messages[2] - '0');
            int minute = (stat_Messages[4] - '0') * 10 + (stat_Messages[5] - '0');
            
            if (hour >= 0 && hour <= 23 && minute >= 0 && minute <= 59) {
              // Store as minutes since midnight
              night_time = hour * 60 + minute;
              char msg[50];
              snprintf(msg, sizeof(msg), "Night time set to %02d:%02d", hour, minute);
              status_Update(String(msg));
            } else {
              status_Update("Invalid time format");
            }
          } else {
            status_Update("Invalid command format. Use NHH:MM");
          }
        }
      }
      break;
    }
    
    default:
      status_Update("Unknown command. Send 'h' for help");
      break;
  }
}